name: A workflow for my Hello Wojobs:
on: push
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "VACLAV"rld file

